version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: air -c .air.toml
    ports:
      - 8080:8080
    environment:
      DB_DATASOURCE: "host=db port=5432 user=app dbname=app password=dev sslmode=disable"
      DB_DSN: postgres://app:dev@db:5432/app?sslmode=disable
      SESSION_TOKEN_COOKIE_KEY: dev_sqlc_tutorial_app_session_token
    volumes:
      - ./:/go/src/github.com/ryoshindo/sqlc-tutorial/backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: dev
