// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: account.sql

package generatedsqlc

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, email, created_at, updated_at) VALUES ($1, $2, $3, $4)
`

type CreateAccountParams struct {
	ID        string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, email, created_at, updated_at FROM accounts WHERE email = $1 LIMIT 1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findById = `-- name: FindById :one
SELECT id, email, created_at, updated_at FROM accounts WHERE id = $1 LIMIT 1
`

func (q *Queries) FindById(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, findById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
