// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package generatedsqlc

import (
	"time"
)

type Account struct {
	ID        string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AccountPassword struct {
	ID        string
	AccountID string
	Hash      []byte
	Salt      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID        string
	AccountID string
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
